#!/usr/bin/env python3
import os
import subprocess
from datetime import datetime
from pathlib import Path

def main():
    try:
        branch = subprocess.check_output(['git', 'branch', '--show-current'], text=True).strip()
    except subprocess.CalledProcessError:
        branch = "main"

    timestamp = datetime.now().strftime("%Y-%m-%d-%H-%M")

    log_dir = Path("log") / branch / timestamp
    log_dir.mkdir(parents=True, exist_ok=True)

    plan_path = log_dir / "plan.md"
    if not plan_path.exists():
        plan_path.write_text("# Session Plan\n\nGenerated by /wiki-decompose or written manually.\n")

    print(log_dir)

if __name__ == "__main__":
    main()
